export const INCREMENT_SECONDS = 'INCREMENT_SECONDS';
export const DECREMENT_SECONDS = 'DECREMENT_SECONDS';
export const INCREMENT_MINUTES = 'INCREMENT_MINUTES';
export const DECREMENT_MINUTES = 'DECREMENT_MINUTES';
export const RESET_TIME = 'RESET_TIME';
export const IS_RUNNING_ON = 'IS_RUNNING_ON';
export const IS_RUNNING_OFF = 'IS_RUNNING_OFF';
