export const INCREMENT_SECONDS = 'INCREMENT_SECONDS';
export const DECREMENT_SECONDS = 'DECREMENT_SECONDS';
export const INCREMENT_MINUTES = 'DECREMENT_MINUTES';
export const DECREMENT_MINUTES = 'DECREMENT_MINUTES';
